ALTER TABLE players 
ADD COLUMN IF NOT EXISTS payment_plan_id UUID REFERENCES plans(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS plan_price DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS plan_start_date DATE;
