ALTER TABLE users DROP COLUMN IF EXISTS is_mock;
ALTER TABLE organizations DROP COLUMN IF EXISTS is_mock;
ALTER TABLE plans DROP COLUMN IF EXISTS is_mock;
ALTER TABLE payments DROP COLUMN IF EXISTS is_mock;
ALTER TABLE clubs DROP COLUMN IF EXISTS is_mock;
